version: "3"

services:
  webapp:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    
    ports:
      - "8000:8000"
    environment:
      MYSQL_HOST: db

    depends_on:
      - db

  db:
    image: mysql:5.7
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "1"
      MYSQL_USER: isucari
      MYSQL_PASSWORD: isucari
      MYSQL_DATABASE: isucari
      TZ: Asia/Tokyo

  # TODO: ローカル用に nginx のコンテナを用意する
  # isucon9-qualify/provisioning/roles/webapp.nginx/files/etc/nginx/nginx.conf